import Head from 'next/head'
import HomePage from "../src/Components/Pages/HomePage";
import AboutUs from "../src/Components/Pages/AboutUs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gas stove</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutUs/>
    </>
  )
}
