import Head from 'next/head'
import Calculation from "../src/Components/Pages/Calculation";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gas stove</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Calculation/>
    </>
  )
}
